### ISSUE TITLE
[FEATURE] Custom Memory Storage

### ISSUE THREAD

**Issue by jrubin11** [crewAIInc/crewAI#2278]
### Feature Area

Agent capabilities

### Is your feature request related to a an existing bug? Please link it here.

NA

### Describe the solution you'd like

Right now, when memory is turned on, all types of memory is stored locally using chroma or sqlite. Even when you opt in to use something like mem0, the other types of memory are still being stored locally. I would like there to be an option to extend the memory storage class and pass that as the memory store for an agent/crew. This would allow for more finetuning and control of agent memory.

The solution could be as simple as exposing a memory storage parameter for the crew/agent.

### Describe alternatives you've considered

I've considered to add support for self managed mem0 instances, for example using a self managed vector store with mem0, but that would only solve part of the problem. I think giving the developer the power to fully manage how memories are stored/retrieved would be incredibly valuable.

### Additional context

NA

### Willingness to Contribute

Yes, I'd be happy to submit a pull request

**Comment by lorenzejay** [comment]
You can extend the memory storage like this:
**https://docs.crewai.com/concepts/memory#example%3A-use-custom-memory-instances-e-g-faiss-as-the-vectordb**

Hope this answers your issue

**Comment by jrubin11** [comment]
> You can extend the memory storage like this: **https://docs.crewai.com/concepts/memory#example%3A-use-custom-memory-instances-e-g-faiss-as-the-vectordb**
> 
> Hope this answers your issue

I understand you can set custom memory storage locations, but what I really mean is customize how memories are saved and retrieved, not just where they are stored. Right now when memory is set to true, all types - short, long, entity, and user (with mem0) are used, but I want complete control on how memories are stored.

**Comment by Vidit-Ostwal** [comment]
I think @Jainish-S, this has been resolve the user_memory, has been depreciated and `external memory` is in place now in the newer version, which I think you can configure directly.

**Comment by Jainish-S** [comment]
@Vidit-Ostwal Yes I got old package due to some other constrains which I found later.

Though I have one doubt.

I am providing memory config to the crew and one of the agent is for information retrieval and provide qa functionality where I have given it a RAG tool. 

When I run the crew the first task run is to retrive information from the knowledge base using the rag tool but instead of that the memory is used and tries to find the information in short memory (not even the from user memory).

Here is some ref:

```python
config = {
        "vector_store": {
            "provider": "qdrant",
            "config": {
                "collection_name": "bcc_user_memory",
                "host": "192.168.0.222",
                "port": 6333,
                "embedding_model_dims": "1536",
            },
        },
        "llm": {
            "provider": "openai",
            "config": {"api_key": os.getenv("OPENAI_API_KEY"), "model": "gpt-4o-mini"},
        },
        "embedder": {
            "provider": "openai",
            "config": {
                "api_key": os.getenv("OPENAI_API_KEY"),
                "model": "text-embedding-3-small",
            },
        },
    }


memory_config={
                "provider": "mem0",
                "config": {
                    "user_id": "jainish",
                    "local_mem0_config": config,
                },
                "user_memory": {},
            },
```

```python
config = {
    "vectordb": {
        "provider": "qdrant",
        "config": {
            "collection_name": "bcc_knowledge",
            "host": "192.168.0.222",
            "port": 6333,
            "vector_dim": "1536",
        },
    },
    "llm": {
        "provider": "openai",
        "config": {"api_key": os.getenv("OPENAI_API_KEY"), "model": "gpt-4o-mini"},
    },
    "embedder": {
        "provider": "openai",
        "config": {
            "api_key": os.getenv("OPENAI_API_KEY"),
            "model": "text-embedding-3-small",
        },
    },
    "chunker": {"chunk_size": 6000, "chunk_overlap": 400, "min_chunk_size": 400},
}

knowledge_tool = RagTool(config=config)
```


```yaml
platform_qa_task:
  description: >
    Analyze the user question: '{user_question}'. 
    Use the 'bcc_knowledge' tool to find relevant information 
    from the BCC platform documentation. Provide a comprehensive and helpful 
    answer based *only* on the information retrieved from the knowledge base.
  expected_output: >
    A clear, concise, and accurate answer to the user's question, strictly based 
    on the information found in the BCC knowledge base via the provided tool. 
    If the information is not found, state that clearly.
  agent: platform_expert
```

```yaml
platform_expert:
  role: >
    Knowledge Assistant
  goal: >
    You are an AI assistant that can answer questions about the Brand Control Center (BCC) 
    platform features, usage, and concepts based on the provided knowledge base.
    It's not necessary to use the bcc_knowledge tool to answer the question.
  backstory: >
    You are an AI assistant with deep knowledge of the BCC platform documentation 
    and functionality, derived solely from the specialized bcc_knowledge tool. 
  verbose: true
  llm: openai/gpt-4o-mini
  allow_delegation: false
  memory: true
```
