### ISSUE TITLE
[BUG] tool input parameter not passed correctly

### ISSUE THREAD

**Issue by iam1492** [crewAIInc/crewAI#2288]
### Description

My agent use simple tool which has only one parameter with wrong way.
for example:
```python
@tool
def stock_info(ticker: str):
    """Useful to get stock infomation.(e.g. market cap, beta, 52-week high, 52-week low, etc.)
    
    Args:
        ticker: The ticker of a company. str
    """
    ticker = yf.Ticker(ticker)
    return ticker.info
```
**This tool's input should be** : {"ticker": "VST"}

But sometimes **input become**: [{"ticker": "VST"}, {"tool_code": "Stock Info", "tool_input": {"ticker": "VST"}}]

Full message from step callback is as follow:
`
Tool Used: Stock Info
  
Tool input: [{"ticker": "VST"}, {"tool_code": "Stock Info", "tool_input": {"ticker": "VST"}}]
  
Message: Thought:Okay, let's start by getting the stock information for Vistra Corp (VST) using the 'Stock Info' tool to get some initial parameters. Action: Stock Info Action Input: {"ticker": "VST"}
  
tool_code
{"tool_code": "Stock Info", "tool_input": {"ticker": "VST"}}
  
Observation: Error: the Action Input is not a valid key, value dictionary.
`

### Steps to Reproduce

1. Use tool with agent

### Expected behavior

Agent use tool with correct way.

### Screenshots/Code snippets

```python
@tool
def stock_info(ticker: str):
    """Useful to get stock infomation.(e.g. market cap, beta, 52-week high, 52-week low, etc.)
    
    Args:
        ticker: The ticker of a company. str
    """
    ticker = yf.Ticker(ticker)
    return ticker.info
```

```python
@agent
def quantitative_analyst_2(self) -> Agent:
	return Agent(
		config=self.agents_config['quantitative_analyst_2'],
		llm=self.get_llm(),
		verbose=True,
		tools=[
			stock_info_tool,
			macro_economic_data,
			basic_financials_from_finnhub,
			financial_statements_from_polygon,
			wacc_calculator_tool,
			expectations_investing,
			#websiteSearchTool,
			#scrape_tool,
		],
		step_callback=lambda step: self.step_callback(step, "Quantitative Analyst 2")
	)
```

My quantative agent use 6~7 tools to calculate stock value.
```yaml
quantitative_analyst_task:
  description: >
    Calculate the Expectations Investing Result of the {company}'s stock.
    Use the provided tools to gather the key financial data which is used to calculate the WACC and Expectations Investing Result.:
      - Obtain the specific macroeconomic data with the Macro Economic Data tool.
      - Obtain the {company}'s info data with the Stock Info tool.
      - Obtain the {company}'s basic financial data with Basic Financials From Finnhub tool.
      - Obtain the {company}'s financial statement with Financial Statements From Polygon tool.
      - Obtain the WACC value with WACC Calculator tool. (Use correct input parameter which is calculated from the former data)
    After obtaning data, using the former data, use Expectations Investing tool with the data.(Use correct input parameter which is calculated from the former data)
    You can also use both WebsiteSearchTool and scrape website tool to get the data from web.(Do not try to read the pdf content from website with scrape website tool as it can exceed maximun token limit)

    IMPORTANT
    - Before using the WACC Calculator and Expectations Investing tool, use other provided tool to get enough data.
    - When performing calculations, all monetary amounts must be converted to dollars before computation. For example, '50 million dollars' should be input as 50000000, and '4b dollars' should be input as 4000000000.
    - Use recent data from financial statements. If the latest financial data is unavailable, you can use the previous year's data for the calculation(and specify the reason).
    - Do not judge the result of Expectations Investing tool(it can be SELL, BUY or HOLD), only judge whether the parameters of the tool used in the calculation are accurate.

  expected_output: >
    The result of the Expectations Investing.

    [Must Contains]
    - Key matrics of result which is given by Expectations Investing tool.
    - Explain the source of the input data.
    - [VERY IMPORTANT] Explain the accuracy of calculated input paramter.
    - [VERY IMPORTANT] Ensure to specify the reliability of the result data.
    
    [OUTPUT FORMAT]
    The final report MUST use Markdown format for optimal readability.
  
  agent: quantitative_analyst
```

### Operating System

Ubuntu 20.04

### Python Version

3.10

### crewAI Version

0.102.0

### crewAI Tools Version

0.33.0

### Virtual Environment

Venv

### Evidence

Different message from agent but same bug:
---

Tool Used: Macro Economic Data

Tool input: [{}, {"tool_code": "Macro Economic Data", "tool_code_kwargs": {}}]

Message: {"No args required."} is not valid.

Thought:My apologies, I made a mistake in the Action Input.  The `Macro Economic Data` tool doesn't require any input arguments, so I should just call it without any input. Let me try that again.
Action: Macro Economic Data
Action Input: {}

{"tool_code": "Macro Economic Data", "tool_code_kwargs": {}}

Observation: Error: the Action Input is not a valid key, value dictionary.

Error: the Action Input is not a valid key, value dictionary.

### Possible Solution

I have no idea, but possibly crewai agent try to follow Langchain style function calling in some reason. 

### Additional context

My quantitative analyst agent make this bug more than others. Other agents use less number of tools. I'm not sure this has any relationship with this bug.
