### ISSUE TITLE
[BUG] crewai create with trailing slash creates broken project

### ISSUE THREAD

**Issue by leoschwarz** [crewAIInc/crewAI#3059]
### Description

This is a minor issue.

When you create a crewai crew and your name ends in a slash (i.e. when you pass a folder name instead of a crew name) the folder does get created but it's not possible to create the virtual environment or run the crew because the `pyproject.toml` is invalid.

### Steps to Reproduce

1. Run `crewai create crew hello/` and confirm the default options.
2. Check the `pyproject.toml` : the package is name "hello/" ad the script is called "hello/". It's also present in module imports.
3. If you try running the crew now it will fail.

### Expected behavior

Either the trailing slash gets normalized away or the create command fails and specifies that the name is invalid.

### Screenshots/Code snippets

```toml
[project]
name = "hello/"
version = "0.1.0"
description = "hello/ using crewAI"
authors = [{ name = "Your Name", email = "you@example.com" }]
requires-python = ">=3.10,<3.14"
dependencies = [
    "crewai[tools]>=0.130.0,<1.0.0"
]

[project.scripts]
hello/ = "hello/.main:run"
run_crew = "hello/.main:run"
train = "hello/.main:train"
replay = "hello/.main:replay"
test = "hello/.main:test"
```

### Operating System

Other (specify in additional context)

### Python Version

3.12

### crewAI Version

0.130.0

### crewAI Tools Version

0.130.0

### Virtual Environment

Venv

### Evidence

![Image](https://github.com/user-attachments/assets/952c0302-14cd-4912-aaf7-42dabed27f09)

### Possible Solution

Either the trailing slash gets normalized away or the create command fails and specifies that the name is invalid.

### Additional context

Fedora Linux 42 (Workstation Edition)
